# For locally developing the add-on as a standalone Docker container 
version: '3.8'

services:
  asterisk:
    image: ghcr.io/tech7fox/amd64-addon-asterisk
    build:
      context: ./asterisk
      network: host
    tty: true
    entrypoint: /init
    init: false
    environment:
      # To connect to the HA API
      HOME_ASSISTANT_URL: http://home-assistant:8123
      HOME_ASSISTANT_TOKEN: <my_secret_token>
    volumes:
      # Mount configuration read by the addon
      - ./asterisk/config.json:/data/options.json:ro
      
      # To avoid having to rebuild the whole image, mount the init files inside it
      # - ./asterisk/rootfs/etc/cont-init.d/asterisk.sh:/etc/cont-init.d/asterisk.sh:ro
      # - ./asterisk/rootfs/etc/cont-init.d/asterisk_mbox.sh:/etc/cont-init.d/asterisk_mbox.sh:ro

  # To test the add-on against an HA instance
  home-assistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:2023.2
    volumes:
      - /etc/localtime:/etc/localtime:ro    # To use host local time
      - config:/config                      # To keep HA configuration between container creations & destructions
    mem_limit: 600m
    stop_grace_period: 5m
    ports:
      - 8123:8123

volumes:
  config: {}